engines:
  radon:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python:
ratings:
  paths:
    - "**.py"
exclude_paths:
- "**/tests/"
- "setup.py"
- "conftest.py"
